import axios from 'axios';
import { ScholarResult, ScholarMetrics } from '@/types';
import crypto from 'crypto';

interface ScholarAdapter {
  searchByTitle(title: string, year?: number): Promise<ScholarResult[]>;
  getMetrics(title: string, author?: string): Promise<ScholarMetrics | null>;
}

class MockScholarAdapter implements ScholarAdapter {
  constructor() {
    console.warn('[SCHOLAR] Using mock adapter.');
  }

  private generateMockHash(str: string): number {
    return crypto.createHash('md5').update(str).digest()[0];
  }

  async searchByTitle(title: string, year?: number): Promise<ScholarResult[]> {
    if (!title) return [];
    
    const hash = this.generateMockHash(title);
    
    return [
      {
        title: title,
        authors: ['Mock Author'],
        year: year || 2023,
        venue: 'Mocked Google Scholar Venue',
        citedBy: (hash * 5) % 500,
        url: `https://scholar.google.com/scholar?q=${encodeURIComponent(title)}`,
        snippet: 'This is a mock snippet generated by the MockScholarAdapter...',
      }
    ];
  }

  async getMetrics(title: string, author?: string): Promise<ScholarMetrics | null> {
    const hash = this.generateMockHash(title + (author || ''));
    
    return {
      citationCount: (hash * 5) % 500,
      hIndex5y: (hash % 10) + 1,
      i10Index: (hash % 20) + 2,
    };
  }
}

class SerperScholarAdapter implements ScholarAdapter {
  private apiKey: string;
  private baseUrl = 'https://google.serper.dev/scholar';

  constructor(apiKey: string) {
    this.apiKey = apiKey;
  }

  async searchByTitle(title: string, year?: number): Promise<ScholarResult[]> {
    try {
      const response = await axios.post(
        this.baseUrl,
        { q: title },
        { headers: { 'X-API-KEY': this.apiKey, 'Content-Type': 'application/json' } }
      );

      const organic = response.data?.organic;
      if (!organic || !Array.isArray(organic)) return [];

      return organic.map((item: any) => {
        // Serper often returns author/venue/year in one string like "A Author, B Author - Journal Name, 2023"
        const publicationInfo = item.publicationInfo || '';
        const parts = publicationInfo.split(' - ');
        
        let authors: string[] = [];
        let venue = '';
        let extractedYear = year;

        if (parts.length > 0) {
          authors = parts[0].split(',').map((a: string) => a.trim());
        }
        if (parts.length > 1) {
          const venueYear = parts[1].split(', ');
          venue = venueYear[0];
          if (venueYear.length > 1) {
            extractedYear = parseInt(venueYear[1], 10);
          }
        }

        return {
          title: item.title,
          authors,
          year: extractedYear,
          venue,
          citedBy: item.citedBy || 0,
          url: item.link,
          snippet: item.snippet,
        };
      });
    } catch (error) {
      console.error(`[Scholar Serper] Error searching title ${title}:`, error);
      return [];
    }
  }

  async getMetrics(title: string, author?: string): Promise<ScholarMetrics | null> {
    const results = await this.searchByTitle(title);
    if (!results || results.length === 0) return null;
    
    // Serper doesn't provide h-index easily without profile search, so we mock it based on citations
    const citations = results[0].citedBy || 0;
    
    return {
      citationCount: citations,
      hIndex5y: Math.floor(Math.sqrt(citations)),
      i10Index: Math.floor(citations / 10),
    };
  }
}

class ProxyScholarAdapter implements ScholarAdapter {
  private proxyUrl: string;

  constructor(proxyUrl: string) {
    this.proxyUrl = proxyUrl;
  }

  async searchByTitle(title: string, year?: number): Promise<ScholarResult[]> {
    try {
      const response = await axios.get(`${this.proxyUrl}/search`, {
        params: { q: title, year }
      });
      return response.data || [];
    } catch (error) {
      console.error(`[Scholar Proxy] Error searching title ${title}:`, error);
      return [];
    }
  }

  async getMetrics(title: string, author?: string): Promise<ScholarMetrics | null> {
    // Requires a Python microservice exposing scholarly
    try {
      const response = await axios.get(`${this.proxyUrl}/metrics`, {
        params: { title, author }
      });
      return response.data || null;
    } catch (error) {
      return null;
    }
  }
}

export const getScholarAdapter = (): ScholarAdapter => {
  if (process.env.SERPER_API_KEY) {
    return new SerperScholarAdapter(process.env.SERPER_API_KEY);
  }
  if (process.env.SCHOLAR_PROXY_URL) {
    return new ProxyScholarAdapter(process.env.SCHOLAR_PROXY_URL);
  }
  return new MockScholarAdapter();
};

export const scholarService = getScholarAdapter();
